"""SSH overlays for ACAS scan prep (unharden) and restore (harden).

Why not Controller API: a PUT would make flush/NOPASSWD/banner the new
desired state. ``/etc/sudoers`` is marked autogenerated by cz-configd, so
visudo-only edits get wiped. We set ``cz-config users/0/nopasswd`` and write
``#includedir`` drop-in ``ACAS_SUDOERS_DROPIN``.

Unharden (SSH, FQDN first):
  1. drop-in + cz-config nopasswd true
  2. wrap ``ACAS_BANNER_FILE`` (ssh_confirm.sh) with ``if [ -t 0 ]``
  3. iptables/ip6tables -F SSHBRUTE; -A ACCEPT **last**
     (cz-config set can rebuild the firewall if we flush first)

Harden:
  1. cz-config nopasswd false
  2. restore banner / sudoers ``*.pre-acas``
  3. rm drop-in
  4. ``nohup systemctl restart cz-configd`` (foreground restart drops SSH)
"""
import re
import shlex
import sys
from typing import Sequence, Union

from config import (
    ACAS_BANNER_FILE,
    ACAS_BANNER_TTY_GUARD,
    ACAS_CZCONFIGD_UNIT,
    ACAS_IPTABLES_BINS,
    ACAS_IPTABLES_CHAIN,
    ACAS_SSH_TIMEOUT,
    ACAS_SUDOERS_DROPIN,
    ACAS_SUDOERS_FILE,
    ACAS_SUDOERS_MARK_BEGIN,
    ACAS_SUDOERS_MARK_END,
    DEBUG,
    SSH_LOG_PREVIEW,
)

from .client import SSHSession

USER_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def _quote_words(values: Sequence[str]) -> str:
    return " ".join(shlex.quote(v) for v in values if v)


class AcasPrep(SSHSession):
    """FQDN-first SSH for ACAS unharden / harden."""

    def unharden(self, host: Union[str, Sequence[str]]) -> str:
        # print(f"DEBUG acas: unharden hosts={host!r}")
        return self._run_script(host, self._unharden_script())

    def harden(self, host: Union[str, Sequence[str]]) -> str:
        # print(f"DEBUG acas: harden hosts={host!r}")
        return self._run_script(host, self._harden_script())

    def _unharden_script(self) -> str:
        user = (self.ssh_user or "").strip()
        if not USER_RE.fullmatch(user):
            raise ValueError(f"Unsafe SSH username for sudoers: {user!r}")
        bins = _quote_words(ACAS_IPTABLES_BINS)
        chain = shlex.quote(ACAS_IPTABLES_CHAIN)
        drop = shlex.quote(ACAS_SUDOERS_DROPIN)
        sudoers = shlex.quote(ACAS_SUDOERS_FILE)
        mark_b = shlex.quote(ACAS_SUDOERS_MARK_BEGIN)
        mark_e = shlex.quote(ACAS_SUDOERS_MARK_END)
        user_q = shlex.quote(f"{user} ALL=(ALL) NOPASSWD: ALL")
        banner = shlex.quote(ACAS_BANNER_FILE)
        guard = ACAS_BANNER_TTY_GUARD
        return f"""
echo STEP_SUDOERS_START
DROP={drop}
SUDOERS={sudoers}
printf '%s\\n' {user_q} > "$DROP"
chmod 440 "$DROP"
if visudo -cf "$DROP" >/dev/null 2>&1; then
  echo STEP_SUDOERS_DROPIN_OK
else
  rm -f "$DROP"
  echo STEP_SUDOERS_FAIL drop-in
  exit 1
fi
if command -v cz-config >/dev/null 2>&1; then
  if cz-config set -j users/0/nopasswd true; then
    echo STEP_CZCONFIG_NOPASSWD_TRUE
  else
    echo STEP_CZCONFIG_NOPASSWD_FAIL
  fi
fi
if grep -qF {mark_b} "$SUDOERS"; then
  echo STEP_SUDOERS_ALREADY
else
  [ -f "${{SUDOERS}}.pre-acas" ] || cp -a "$SUDOERS" "${{SUDOERS}}.pre-acas"
  printf '\\n%s\\n%s\\n%s\\n' {mark_b} {user_q} {mark_e} >> "$SUDOERS"
  if visudo -cf "$SUDOERS" >/dev/null 2>&1; then
    echo STEP_SUDOERS_OK
  else
    mv "${{SUDOERS}}.pre-acas" "$SUDOERS"
    echo STEP_SUDOERS_FAIL visudo
    exit 1
  fi
fi

echo STEP_BANNER_START
f={banner}
if [ ! -f "$f" ]; then
  echo STEP_BANNER_SKIP missing "$f"
else
if grep -qF {shlex.quote(guard)} "$f"; then
  echo "STEP_BANNER_ALREADY $f"
else
  [ -f "${{f}}.pre-acas" ] || cp -a "$f" "${{f}}.pre-acas"
  tmp="${{f}}.acas.$$"
  awk '
    {{ print }}
    !ins && /SSH_CLIENT/ {{ print "{guard}"; ins=1 }}
    ins && !closed && /^done[[:space:]]*$/ {{ print "fi"; closed=1 }}
  ' "$f" > "$tmp"
  if bash -n "$tmp" 2>/dev/null; then
    mv "$tmp" "$f"
    echo "STEP_BANNER_OK $f"
  else
    rm -f "$tmp"
    echo STEP_BANNER_SKIP bash -n "$f"
  fi
fi
fi

echo STEP_IPTABLES_START
for bin in {bins}; do
  if "$bin" -w -n -L {chain} >/dev/null 2>&1; then
    "$bin" -w -F {chain}
    "$bin" -w -A {chain} -j ACCEPT
    echo STEP_IPTABLES_OK "$bin"
    "$bin" -w -S {chain} || true
  else
    echo STEP_IPTABLES_SKIP "$bin" no {chain} chain
  fi
done
echo STEP_UNHARDEN_DONE
"""

    def _harden_script(self) -> str:
        drop = shlex.quote(ACAS_SUDOERS_DROPIN)
        banner = shlex.quote(ACAS_BANNER_FILE)
        sudoers = shlex.quote(ACAS_SUDOERS_FILE)
        unit = shlex.quote(ACAS_CZCONFIGD_UNIT)
        return f"""
if command -v cz-config >/dev/null 2>&1; then
  cz-config set -j users/0/nopasswd false && echo STEP_CZCONFIG_NOPASSWD_FALSE || true
fi
echo STEP_BANNER_RESTORE
f={banner}
if [ -f "${{f}}.pre-acas" ]; then
  mv "${{f}}.pre-acas" "$f"
  echo "STEP_BANNER_RESTORED $f"
fi
echo STEP_SUDOERS_REMOVE
rm -f {drop}
SUDOERS={sudoers}
if [ -f "${{SUDOERS}}.pre-acas" ]; then
  mv "${{SUDOERS}}.pre-acas" "$SUDOERS"
  echo STEP_SUDOERS_RESTORED
else
  sed -i '/{ACAS_SUDOERS_MARK_BEGIN}/,/{ACAS_SUDOERS_MARK_END}/d' "$SUDOERS" || true
fi
echo STEP_CZCONFIGD_RESTART
nohup systemctl restart {unit} >/dev/null 2>&1 &
echo STEP_HARDEN_DONE
"""

    def _run_script(self, host: Union[str, Sequence[str]], script: str) -> str:
        if DEBUG:
            print(
                f"      DEBUG acas: script_len={len(script)} timeout={ACAS_SSH_TIMEOUT}",
                file=sys.stderr,
            )
        result = self._with_ssh_endpoints(
            host,
            lambda c, s=script: self._sudo_script(c, s, timeout=ACAS_SSH_TIMEOUT),
            error="SSH failed",
        )
        rc, text = result
        # print(f"DEBUG acas: rc={rc} steps={[ln for ln in text.splitlines() if ln.startswith('STEP_')]}")
        if "STEP_HARDEN_DONE" in text or "STEP_UNHARDEN_DONE" in text:
            return text
        if rc != 0 or "STEP_SUDOERS_FAIL" in text or "STEP_BANNER_FAIL" in text:
            steps = " ".join(ln for ln in text.splitlines() if ln.startswith("STEP_"))
            raise ValueError(
                f"ACAS script failed (exit {rc}): {(steps or text.strip())[:SSH_LOG_PREVIEW]}"
            )
        return text
